version: "3.9"

services:
  db:
    container_name: telegram-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "shops"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - telegram-bot
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - telegram-bot-postgres-data:/var/lib/postgresql/data/  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5   

networks:
  telegram-bot:

volumes:
  telegram-bot-postgres-data: